export enum EventNames {
  FOCUS = 'FOCUS',
  SELECT = 'SELECT',
  MOUSE_ENTER = 'MOUSE_ENTER',
  MOUSE_MOVE = 'MOUSE_MOVE',
  MOUSE_LEAVE = 'MOUSE_LEAVE',
}

export enum DataTypes {
  FOCUS_FORMULA = 'FOCUS_FORMULA',
  SELECT_FORMULA = 'SELECT_FORMULA',
  MOUSE_ENTER_CELL = 'MOUSE_ENTER_CELL',
  SELECT_CELL = 'SELECT_CELL',
}
